# Generated by Django 2.2.7 on 2019-11-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default='2019-08-11', verbose_name='date published'),
            preserve_default=False,
        ),
    ]
